<?php

/**
* Drupal core hooks
*/


/**
* Implementation of hook_menu().
*/
function bubbletree_menu() {
  $items['bubble'] = array(
    'title' => 'Rozklikávací rozpočet',
    'page callback' => 'bubbletree_create_app',
    //'file' => 'dailybread_config.inc',
    'access callback' => TRUE,
    'menu_name' => 'main-menu',
  );
  
  return $items;
}

/**
*
*/
function bubbletree_create_app() {
  //include js + css
  drupal_add_js(drupal_get_path('module', 'bubbletree') . '/lib/jquery-1.5.2.min.js');
  drupal_add_js("https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js",'external');
  drupal_add_js(drupal_get_path('module', 'bubbletree') . '/lib/jquery.history.js');
  drupal_add_js(drupal_get_path('module', 'bubbletree') . '/lib/raphael.js');
  drupal_add_js(drupal_get_path('module', 'bubbletree') . '/lib/vis4.js');
  drupal_add_js(drupal_get_path('module', 'bubbletree') . '/lib/Tween.js');
  drupal_add_js(drupal_get_path('module', 'bubbletree') . '/lib/jquery.tablesorter.min.js');
  
  drupal_add_js(drupal_get_path('module', 'bubbletree') . '/bubbletreem2.js');
  
  drupal_add_css('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/ui-lightness/jquery-ui.css','external');
  drupal_add_css(drupal_get_path('module', 'bubbletree') . '/blue/style.css',array('group' => CSS_DEFAULT, 'every_page' => FALSE));
  //drupal_add_html_head_link(array('href' => drupal_get_path('module', 'bubbletree') . '/blue/style.css', 'rel' => 'stylesheet', 'type' => 'text/css', 'media' => 'all'));
  drupal_add_html_head_link(array('href' => drupal_get_path('module', 'bubbletree') . '/bubbletreem.css', 'rel' => 'stylesheet', 'type' => 'text/css', 'media' => 'all'));
  
  drupal_add_js(
  	"$(function() { 		
	   //before ajax call
	   $('#bubbletree-ajax-loader').html('<img src=\"".drupal_get_path('module', 'bubbletree') . "/ajax-loader.gif\" alt=\"Wait\" /> Nahrávám data rozpočtu, může to chvíli trvat ...');
       $.ajax({
		  url: '".drupal_get_path('module', 'bubbletree') . "/data" . (isset($_GET['scope']) ? "b9" : "b12") . ".json',
		  dataType: 'json',
		  success: function (d) {	
			new BubbleTree({
				data: d,
				container: '.bubbletree',
				maxNodesPerLevel: 15
			});
		  },
		});
	});
	$(function() {
		$( '#tabs' ).tabs();
	});
	",'inline');
  $html = _body_markup();
  return theme('html_tag',$html);
}

function _body_markup() {
$meth = _meth_text();
$div = array(
    'element' => array(
       '#tag' => 'div',
       '#value' => '
	<div id="bs-breadcrumbs">Rozpočet</div>
	<div id="tabs">
	  <ul>
	    <li><a href="#tabs-1">Graf</a></li>
	    <li><a href="#tabs-2">Tabulka</a></li>
	    <li><a href="#tabs-3">Lidé</a></li>
	    <li><a href="#tabs-4">Metodika</a></li>
	  </ul>
	  <div id="tabs-1">
	  	    <div id="bubbletree-ajax-loader"></div>
			<div class="bubbletree-wrapper" style="width:900px;height:600px">
				<div class="bubbletree"></div>
			</div>
	  </div>
	  <div id="tabs-2">
			<div id="bs-table-ajax-loader"></div>
			<div id="bs-table"></div>
	  </div>
	  <div id="tabs-3">
			<div id="bs-people-ajax-loader"></div>
			<div id="bs-people"></div>
	  </div>
	  <div id="tabs-4">
			<div id="bs-methodology">'.$meth.'</div>
	  </div>
	</div>
	  ',
	),
);
return $div;
}

/**
*
*/
function _meth_text() {
  $html = '
<h2>Metodika „rozklikávacího“ rozpočtu</h2>
<p>Metodika tabulek vychází z třídění výdajů, které používá státní správa, a které je stanoveno zejména zákonem č. 218/2000Sb., a vyhláškou č. 353/2002 Sb. (dále jen Vyhláška).</p>
<p>Zdrojem dat byla veřejně přístupná databáze IDB Aris / ÚFIS spravovaná Ministerstvem financí České republiky.</p>
<p>Analýza je zaměřena na přehledné zobrazení výdajů státního rozpočtu České republiky a to formou časových řad a dekompozice státního rozpočtu/kapitol/organizací/typu výdaje. Z důvodů vizuálního zobrazení proporcí na jedné straně a exaktností na straně druhé byly zvoleny jak grafické vyjádření hodnot tak i tabulky, oboje v „rozklikávací“ verzi.</p>
<h3>Popis jednotlivých úrovní</h3>
<h4>První úroveň</h4>
<p>Rozčlenění výdajů státního rozpočtu celkem (první řádek nahoře) na výdaje dle jednotlivých kapitol (odpovědnostní třídění, příloha A Vyhlášky).</p>
<h4>Druhá úroveň</h4>
<p>Kapitoly se dále člení na výdaje celkem dle jednotlivých státních organizací (organizační složky státu i státní příspěvkové organizace) dané jednoznačným identifikačním číslem organizace.</p>
<p>Tato úroveň je vhodná pro přehled o jednotlivých organizací v rámci kapitoly a jejich „významnosti“ měřené celkovými výdaji.</p>
<h4>Třetí úroveň</h4>
<p>je zaměřena na rozčlenění výdajů jednotlivých organizací dle druhového třídění rozpočtové skladby (příloha B Vyhlášky)</p>
<table>
<thead>
  <tr><td>Část</td><td>Detail</td><td>Položka</td></tr>
</thead>
<tbody>
  <tr><td rowspan="3">Provozní výdaje</td><td>Běžné provozní výdaje</td><td>5000-5199</td></tr>
  <tr><td>Náhrady zaměstnancům v době nemoci</td><td>5424</td></tr>
  <tr><td>Převody do FKSP</td><td>5342</td></tr>
  <tr><td>Investiční výdaje</td><td>Investiční výdaje</td><td>6100-6299</td></tr>
  <tr><td rowspan="2">Neinvestiční transfery</td><td>Neinvestiční transfery</td><td>5201-5250</td></tr>
  <tr><td>Neinvestiční transfery</td><td>5311-5790</td></tr>
  <tr><td rowspan="2">Investiční transfery</td><td>Investiční transfery</td><td>6300-6359</td></tr>
  <tr><td>Investiční transfery</td><td>6371-6789</td></tr>
  <tr><td rowspan="4">Převody fondům</td><td>Neinvestiční převody fondům</td><td>5341+5343-5349</td></tr>
  <tr><td>Investiční transfery</td><td>5901-5909</td></tr>
  <tr><td>Investiční transfery</td><td>6361</td></tr>
  <tr><td>Investiční transfery</td><td>6901-6909</td></tr>
  
</tbody>
</table>
<h4>Čtvrtá úroveň</h4>
<p>Zobrazuje výdaj dle odvětvového třídění rozpočtové skladby (příloha C Vyhlášky).</p>
  ';
  return $html;
}

	
?>
	

